### ISSUE TITLE
Work for Docker

### ISSUE THREAD

**Issue by Joly0** [phipzzz/crowdsec-dyndns-ip-whitelister#2]
Hey, i would like to use your tool, but i am running crowdsec in a docker container. Is it possible to use your tool there aswell? Or would it be possible to adjust it so it would work with docker?

Thanks for your work and the tool :D

**Comment by fliprocks** [comment]
Hey @Joly0,
Good idea. This was not covered by the script until now. It only required minor changes. Would you mind testing it?

[This Gist](https://gist.github.com/phipzzz/3e4a7540ba4cec4e25a7b9e8da6e5085) contains the updated version. You might need to update the container name in line 6 (`crowdsecContainerName = "crowdsec"`). Additionally, you will need to bind mount a given path on the host machine to the /etc/crowdsec directory of your container. E.g. like following in a docker-compose.yml

```yml
services:
    crowdsec:
        image: "crowdsecurity/crowdsec:latest"
        volumes:
            - "/opt/docker/crowdsec/log:/var/log:ro"
            - "/opt/docker/crowdsec/data/:/var/lib/crowdsec/data/"
            # Following line would be important and depends on your local setup
            - "/opt/docker/crowdsec/crowdsec/:etc/crowdsec"
        container_name: crowdsec
```

The rest of the procedure would be the same. You'll need a cronjob to automatically run the Python script. The scrpipt needs to be placed within the directory the container is accessing for its mounts. Below, you can find my directory structure including the bind mounts.

```bash
├── crowdsec        # important directory 
│   ├── acquis.d
│   ├── acquis.yaml
│   ├── appsec-configs
│   ├── appsec-rules
│   ├── collections
│   ├── config.yaml
│   ├── console
│   ├── console.yaml
│   ├── contexts
│   ├── dev.yaml
│   ├── hub
│   ├── local_api_credentials.yaml
│   ├── notifications
│   ├── online_api_credentials.yaml
│   ├── parsers
│   ├── patterns
│   ├── postoverflows
│   ├── profiles.yaml
│   ├── scenarios
│   ├── simulation.yaml
│   └── user.yaml
├── currentIP        # will be created during the first run       
├── data
│   ├── crowdsec.db
│   ├── GeoLite2-ASN.mmdb
│   ├── GeoLite2-City.mmdb
│   └── trace -> /staging/var/lib/crowdsec/data/trace
├── docker-compose.yml
├── log
└── publicIpWhitelister-docker.py        # the script itself
```

I tested it successfully on my dev environment, but it would be great to have your feedback as well.
